function outPath = exportAnsysBoundaryCondition(feaDir, erosionMatrix, peakShaftLoad_MNm)
%EXPORTANSYSBOUNDARYCONDITION Write the peak rotor bending load as an APDL
%   command snippet + a plain CSV, so an ANSYS Mechanical / Workbench
%   journal can import the boundary condition programmatically instead of
%   a manual UI entry (REQ-SYS-01).

    if ~exist(feaDir, 'dir')
        mkdir(feaDir);
    end

    radialPos_m = erosionMatrix(1);
    depth_mm    = erosionMatrix(2);

    % Convert the rotor bending moment (MNm) into an equivalent applied
    % force (N) for a simple face-load approximation at the erosion
    % station, using the moment arm from the root to the defect location.
    % F = M / r   (very simplified 1D reduction used purely to seed the
    % Workbench "Force" boundary condition; refine with the real load path
    % / moment-to-force mapping for your blade geometry).
    momentArm_m = max(radialPos_m, 1);
    equivalentForce_N = (peakShaftLoad_MNm * 1e6) / momentArm_m;

    csvPath = fullfile(feaDir, 'boundary_condition_export.csv');
    fid = fopen(csvPath, 'w');
    fprintf(fid, 'parameter,value,unit\n');
    fprintf(fid, 'erosion_radial_position,%.2f,m\n', radialPos_m);
    fprintf(fid, 'erosion_pitting_depth,%.2f,mm\n', depth_mm);
    fprintf(fid, 'peak_rotor_bending_moment,%.4f,MNm\n', peakShaftLoad_MNm);
    fprintf(fid, 'equivalent_applied_force,%.2f,N\n', equivalentForce_N);
    fprintf(fid, 'yield_strength_threshold,250,MPa\n');
    fclose(fid);

    apdlPath = fullfile(feaDir, 'boundary_condition.mac');
    fid = fopen(apdlPath, 'w');
    fprintf(fid, '! Auto-generated by exportAnsysBoundaryCondition.m - DO NOT hand-edit\n');
    fprintf(fid, '! Erosion coordinate: %.2f m span, %.2f mm pitting depth\n', radialPos_m, depth_mm);
    fprintf(fid, '! Source: pipeline_orchestrator.m, peak rotor bending moment = %.4f MNm\n\n', peakShaftLoad_MNm);
    fprintf(fid, '*SET,EROSION_RADIAL_M,%.4f\n', radialPos_m);
    fprintf(fid, '*SET,EROSION_DEPTH_MM,%.4f\n', depth_mm);
    fprintf(fid, '*SET,APPLIED_FORCE_N,%.4f\n', equivalentForce_N);
    fprintf(fid, '*SET,YIELD_LIMIT_MPA,250\n\n');
    fprintf(fid, '! In Workbench Mechanical, reference these parameters from a\n');
    fprintf(fid, '! Command (APDL) snippet under the Static Structural branch, e.g.:\n');
    fprintf(fid, '!   /PREP7\n');
    fprintf(fid, '!   CMSEL,S,ErosionZone      ! named selection at the erosion station\n');
    fprintf(fid, '!   SF,ALL,PRES,APPLIED_FORCE_N/AREA_OF_SELECTION\n');
    fclose(fid);

    outPath = apdlPath;
end
